### PR TITLE
Add Linux support

### PR DESCRIPTION
**Pull request by nyorem**

### CODE REVIEW

**Comment by Rinnegatamante** [comment]
Looks like i'm having several issues compiling the source after merging your pull.
Errors came out cause macro expansion on Win and other errors probably caused by missing includes on win.

**Comment by nyorem** [comment]
I don't have a Windows machine at hand to test it but try to apply this [diff](https://github.com/Rinnegatamante/VitaPad/files/436852/windows.txt) (I forgot `__VA_ARGS__` in the macros).

**Comment by Rinnegatamante** [comment]
Should be fixed now.

**Comment by Rinnegatamante** [comment]
First time i've seen the lib you used for linux porting, may i ask you how to simulate mouse movement/click?

OR, if you want, take a look at latest commits and feel free to adapt the code to linux :D

**Comment by nyorem** [comment]
It's the Xlib (https://tronche.com/gui/x/xlib/) that uses the X11 windowing system.
I will try have a look at it this week-end.

**Comment by xerpi** [comment]
Please don't use the X server to fake input..
There are a lot of reasons, one is that I don't think that will work in (X)Wayland.
Also this requires the X server to be running, and it won't work if you are for example running a Wayland compositor without XWayland or on a virtual terminal.
To fix this you should use uinput instead (http://thiemonge.org/getting-started-with-uinput).

**Comment by nyorem** [comment]
Ok, thanks for the recommendation, I will have a look at it.

**Pull request merged**
